name: Windows-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "py${{ matrix.python-version }} on ${{ matrix.os }}"
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]') && !contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install --no-progress python --version 3.8
          choco --yes install --no-progress GnuWin
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
          python -m pip install tox

      - name: Run tests
        run: |
          tox -e py38-test
